# Exercise 1 

In this exercise, we will work with the `winemag-data-130k-v2.csv` data file. This file contains information about wine. The goal is to explore this data set and build regression models with `TensorFlow`. For more information about the data file, see this [link](https://www.kaggle.com/datasets/zynicide/wine-reviews/data).

### Exercise 1(a) (2 points)

Load the following libraries as follows:

```
import pandas as pd 
import numpy as np

import tensorflow as tf
```

In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `wine_df`.

In [2]:
wine_df = pd.read_csv('winemag-data-130k-v2.csv')
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Exercise 1(c) (3 points)

Using the `string` library, remove all the punctuation of the `description` column and store the results in another column called `description_clean`.

In [3]:
import string

wine_df['description_clean'] = wine_df['description'].str.replace(f'[{string.punctuation}]','', regex=True)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...

### Exercise 1(d) (8 points)

Remove stopwords, pronouns, and other words from `description_clean` and store in another column called `'description_clean_1'`. Consider the below list as the stopwords list. Also, convert all the words to lowercase.

```
stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 
'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 
'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 
'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves',
 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are',
 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing',
 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 
'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 
'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 
'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 
'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 
's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y',
 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 
'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn',
 "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 
'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't",  'drink', 'now', 'wine', 'flavor', 'flavors']
```

In [4]:
stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 
'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 
'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 
'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves',
 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are',
 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing',
 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 
'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 
'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 
'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 
'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 
's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y',
 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 
'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn',
 "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 
'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't",  'drink', 'now', 'wine', 'flavor', 'flavors']

def clean_text(text):
    #tokenize text
    tokens = text.lower().split()
    
    #remove stopwords
    tokens = [word for word in tokens if word not in stopwords]
    
    return ' '.join(tokens)

wine_df['description_clean_1'] = wine_df['description_clean'].apply(clean_text)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...

### Exercise 1(e) (6 points)

Based on the results from part 1(d), we see digits in some of the text in `description_clean_1`. Remove all the digits from `description_clean_1` and store the results in another column `description_clean_2` in the `wine_df` data frame.

In [5]:
wine_df['description_clean_2'] = wine_df['description_clean_1'].str.replace(r'\d+', '', regex=True)
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,description_clean,description_clean_1,description_clean_2
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...,aromas include tropical fruit broom brimstone ...
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,This is ripe and fruity a wine that is smooth ...,ripe fruity smooth still structured firm tanni...,ripe fruity smooth still structured firm tanni...
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Tart and snappy the flavors of lime flesh and ...,tart snappy lime flesh rind dominate green pin...,tart snappy lime flesh rind dominate green pin...
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Pineapple rind lemon pith and orange blossom s...,pineapple rind lemon pith orange blossom start...,pineapple rind lemon pith orange blossom start...
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Much like the regular bottling from 2012 this ...,much like regular bottling 2012 comes across r...,much like regular bottling comes across rathe...

### Exercise 1(f) (10 points)

Use `Word2Vec` from `gensim` library to create embedding for `description_clean_2`. Use the following configuration for `Word2Vec`:

```
Word2Vec(sentences=tokenized_texts, vector_size=200, window=5, min_count=1, workers=4)
```

Store the embedding in a matrix called `X`.

In [6]:
import gensim

from gensim.models import Word2Vec

tokens = wine_df['description_clean_2'].apply(lambda x: x.split())

# train word2vec
word2vec_model = Word2Vec(sentences=tokens, vector_size=200, window=5, min_count=1, workers=4)

# embed text
def get_avg_word2vec(token_list, model, vector_size):
    #remove out-of-vocab words
    valid_tokens = [word for word in token_list if word in model.wv]
    
    if not valid_tokens:
        return np.zeros(vector_size)
    
    return np.mean(model.wv[valid_tokens], axis=0)

# apply function to get embeddings
X = tokens.apply(lambda x: get_avg_word2vec(x, word2vec_model, 100))
X = np.vstack(X.values)
print(X[:5])

[[-2.21258640e-01  8.16602588e-01  2.63399512e-01 -4.89805758e-01
  -8.13781172e-02  1.09690517e-01 -2.60327578e-01 -6.48602724e-01
   7.44764954e-02  9.89858627e-01 -3.55503112e-01 -4.13487434e-01
  -4.79547143e-01  1.82212796e-02  3.36694658e-01 -2.70134471e-02
  -1.08013801e-01 -1.39418751e-01  8.79417807e-02  5.20571694e-02
  -2.94788122e-01  1.78825200e-01  4.60609972e-01  8.19989815e-02
  -1.29141343e+00  6.03137493e-01 -1.24768622e-01  1.05117786e+00
   6.08385980e-01 -2.93202996e-01 -9.88830179e-02 -5.49607396e-01
   1.68183729e-01 -1.88717529e-01 -1.17558777e-01 -2.31610656e-01
  -1.70048088e-01  1.03508711e+00  6.50917828e-01  4.16413039e-01
   4.84732054e-02  4.04526711e-01  5.25767803e-01 -4.45016623e-01
  -6.86407924e-01  4.47799683e-01  3.12848091e-01 -6.18389845e-01
  -1.01854287e-01  9.85040441e-02 -6.80695698e-02 -2.94497550e-01
   2.76068151e-01 -1.19565308e+00 -3.80564511e-01 -2.55689949e-01
  -3.40478361e-01 -2.07515150e-01 -6.60932511e-02  1.49592474e-01
  -6.48403540e-02 -2.61251777e-01  1.29514039e-01 -4.36797589e-01
   7.95209050e-01 -3.84666353e-01 -7.96615928e-02  1.20944180e-01
  -1.74510986e-01 -3.48155290e-01  3.09204087e-02 -4.36277121e-01
   1.37911022e-01 -2.21412018e-01 -8.43569934e-02 -3.63079011e-01
   1.00815691e-01  3.92671853e-01  5.31241238e-01  1.76268056e-01
  -2.20222339e-01 -4.25208718e-01  2.69890368e-01 -4.85406727e-01
  -1.06609389e-01 -3.25263321e-01  3.09438389e-02  4.53459062e-02
  -6.92692041e-01 -9.32194218e-02  9.96060744e-02 -3.23777407e-01
   5.25069773e-01 -9.10125732e-01 -3.84003043e-01 -6.42670453e-01
  -7.88195848e-01  1.08028626e+00 -6.39893055e-01 -3.24442178e-01
   2.58359492e-01 -1.00838594e-01 -4.09975469e-01  4.68721211e-01
   3.66614670e-01  4.61945176e-01 -4.89792466e-01  9.24286374e-04
   6.21704221e-01  2.09482148e-01  5.53632453e-02  1.29652917e-01
  -4.43357736e-01  2.39385873e-01 -6.24905415e-02  4.38749641e-01
  -4.69511986e-01  5.63250244e-01  1.48542225e-01  7.42513537e-02
  -2.99733192e-01  4.02440364e-03 -6.67769760e-02  8.55784211e-03
   6.33330762e-01  6.75391436e-01  3.12033445e-01  4.64812696e-01
  -8.86044919e-01 -4.65370446e-01  1.09886304e-01 -4.62313384e-01
   7.10106611e-01  2.78607726e-01  6.38725042e-01  1.32932618e-01
   5.77624366e-02  4.93245482e-01  3.88496727e-01  2.17704251e-01
  -3.24748456e-01  1.81821901e-02 -4.62573737e-01 -2.02743754e-01
   8.51466119e-01  4.76361722e-01  1.53079003e-01  7.94227328e-03
  -6.84914351e-01  6.43661916e-02 -7.47831464e-01  1.59934357e-01
  -3.42694926e-03  2.93054193e-01  6.05878651e-01 -6.37170970e-02
  -3.26281279e-01  4.60030399e-02  7.32970610e-02 -7.54614472e-01
  -4.28986877e-01 -6.78216934e-01  4.36053813e-01  9.58636254e-02
   8.35785046e-02 -3.06402266e-01 -1.90013140e-01 -3.34435366e-02
   5.26583731e-01 -2.56323311e-02  2.77637064e-01  1.31610483e-01
   5.33265471e-01 -1.08006068e-01 -3.01710457e-01 -5.01141787e-01
   7.89364159e-01 -5.40290654e-01  3.65111709e-01  3.19555044e-01
  -4.15720254e-01  1.88776508e-01  8.64577711e-01 -4.04612780e-01
   7.30578080e-02 -5.45043051e-01 -3.77520978e-01  1.16672322e-01
  -5.35360396e-01 -1.37206316e-02 -1.86702847e-01 -9.01628613e-01
   6.18074894e-01  1.94820672e-01 -8.06037247e-01  7.38525689e-01
   3.33521366e-02  3.65380257e-01 -8.71993124e-01 -2.89822817e-01]
 [ 5.11140764e-01  1.68649480e-01 -1.46199033e-01 -1.01396227e+00
   1.40243876e+00  1.47385076e-01  1.76506385e-01 -5.06907463e-01
   8.97972703e-01  4.31201726e-01  7.68609196e-02  8.56777206e-02
  -9.52044308e-01 -3.01096410e-01  2.04095095e-01 -3.16212684e-01
  -7.75590241e-01  1.27996966e-01  3.72496635e-01 -5.78091443e-01
  -3.88593584e-01  4.03762102e-01  4.92800772e-01  4.27783161e-01
  -7.17675984e-01  6.44990981e-01  5.16540110e-01 -7.33366236e-02
   2.23954931e-01  3.59987110e-01  1.95907861e-01 -6.73665881e-01
  -4.08734679e-01 -9.01266113e-02  1.01959035e-02  9.09950212e-02
  -6.06843308e-02  2.92036116e-01  2.27447912e-01  7.65635520e-02
   5.34854829e-01  1.25840217e-01 -2.74864107e-01  4.54502925e-02
  -4.82882261e-01  1.04575825e+00  8.79575729e-01 -1.73402429e-01
   3.20722491e-01 -2.09719285e-01 -1.10392317e-01 -1.18099117e+00
   5.42793691e-01  3.43602777e-01 -4.81836528e-01  7.55602658e-01
   2.09659219e-01  6.14273787e-01  6.60915226e-02  1.66474700e-01
  -2.07038954e-01 -1.41614687e+00  9.73309457e-01  2.86470413e-01
   9.17124093e-01 -4.16427329e-02  1.70204565e-01 -7.07695663e-01
   2.04946727e-01 -1.54319808e-01 -7.27742240e-02  1.09705389e-01
  -3.56857836e-01  2.90692747e-01 -1.92228377e-01 -1.27452075e+00
   7.51448810e-01 -4.01852936e-01  5.33947647e-01 -6.55568838e-01
   8.87615979e-01  2.13240728e-01 -6.25180423e-01 -4.14751053e-01
   5.78849614e-01  4.70749252e-02 -3.39965969e-02 -3.04613769e-01
  -2.67438561e-01  3.41495126e-01 -3.37860137e-01 -4.93818879e-01
   9.36958194e-02  6.35024309e-02 -6.73649490e-01 -7.53688514e-02
  -5.57362199e-01  2.61090547e-01 -3.40532362e-01 -1.20971501e-01
  -5.11924565e-01 -7.85040617e-01  1.40638286e-02  1.19593307e-01
   1.28020480e-01  4.78463084e-01 -2.27878764e-01 -7.96841681e-01
   1.14398934e-01  1.05348146e+00 -2.57842302e-01 -1.86034083e-01
   5.79776108e-01  6.69027790e-02 -5.28308272e-01 -4.01840061e-01
  -9.10610795e-01  4.31081116e-01  6.50110722e-01  6.60794795e-01
   3.96426171e-01  1.18975304e-01 -1.19651206e-01 -9.46350574e-01
  -3.29618812e-01  1.27782762e+00  2.28314355e-01  3.42732280e-01
  -5.76571703e-01 -7.40101576e-01  3.89962971e-01 -1.20098342e-03
   1.24673665e-01 -2.56374925e-01  3.80087823e-01  2.80792769e-02
  -4.35094029e-01  8.62762481e-02 -1.75011277e-01  3.17964971e-01
  -1.38320315e+00 -2.39017457e-01 -3.02429385e-02  2.17989370e-01
   3.73314947e-01  2.41925940e-01  2.82168776e-01 -7.23014414e-01
   7.46723339e-02 -8.51199389e-01 -7.61170924e-01  1.20604241e+00
  -7.27064386e-02  1.55847803e-01  2.31662929e-01 -1.14917135e+00
   5.99522710e-01 -5.48023105e-01 -2.42279336e-01 -2.66792744e-01
  -2.89285094e-01 -3.56709749e-01  1.67491749e-01  4.33494478e-01
   5.92734158e-01 -8.14855993e-01 -1.43985465e-01  4.07065094e-01
   3.29440445e-01  2.08757252e-01  9.99568939e-01 -4.43642706e-01
  -2.41465822e-01  7.44212627e-01  4.57833350e-01 -1.07519674e+00
   3.54920298e-01 -7.25873768e-01 -2.68017519e-02 -3.88590634e-01
  -6.73188686e-01 -5.76470196e-01  1.07075787e+00  6.44531026e-02
  -9.28490758e-02  1.83704440e-02  3.08692843e-01  2.01035023e-01
  -4.50887114e-01  4.07762915e-01 -1.22836515e-01 -5.10848701e-01
   4.51643229e-01  5.56369305e-01 -7.14837313e-01 -2.72966504e-01
   1.18032016e-01  2.04056174e-01  3.73259157e-01  1.36665955e-01]
 [-6.19180977e-01  6.58983350e-01  3.32645833e-01 -1.82919860e-01
   3.83526981e-01  7.91342482e-02 -8.79503414e-02 -8.32280815e-01
  -3.84684563e-01  3.24083507e-01  2.10197240e-01  1.05593048e-01
   4.13153842e-02 -6.31620049e-01  8.05019975e-01 -1.86842531e-01
  -1.05496950e-01 -4.40222055e-01  2.45147571e-01 -3.76793891e-01
  -7.01014176e-02 -8.67717192e-02  6.77861512e-01  8.13724995e-02
  -1.14571095e+00  8.62046063e-01 -1.54068798e-01  5.92968524e-01
   8.41200948e-01  3.03985864e-01 -2.80751795e-01 -7.37085283e-01
   1.82662695e-03 -1.53391108e-01 -6.12986088e-01  2.29097158e-01
  -2.11435288e-01  6.26238883e-01  9.42899585e-01 -8.49513337e-02
  -4.43865269e-01  3.87573510e-01  7.27165997e-01 -4.55686122e-01
  -8.76407146e-01  9.34174180e-01  8.91025543e-01 -2.80820370e-01
   2.86940843e-01 -1.07645236e-01  4.43365246e-01 -6.04136407e-01
   4.47940752e-02 -1.95065126e-01 -5.27499437e-01  4.40591164e-02
  -5.10407031e-01  3.21219154e-02 -4.94435370e-01  4.01444584e-01
  -1.35927722e-01  2.71390140e-01  3.63944173e-02 -1.40714139e-01
   4.51135397e-01  3.28222573e-01 -6.32313251e-01 -4.18901533e-01
  -1.45096704e-01 -1.27057051e-02 -2.42685705e-01 -2.70355165e-01
   5.91972530e-01 -1.84619084e-01  5.09499237e-02 -1.45814985e-01
   2.80788660e-01 -5.10812998e-02 -4.35455054e-01  6.09057128e-01
  -3.35566521e-01 -4.80325073e-01  3.22854072e-02 -7.37726510e-01
   4.87519830e-01  9.70691517e-02 -4.25828040e-01  9.00971413e-01
  -6.40958130e-01  9.38305035e-02 -3.33372861e-01 -1.63445011e-01
   5.12189448e-01  1.29899338e-01 -7.16909021e-02  4.78914455e-02
  -7.98598289e-01  6.70858383e-01 -4.24630880e-01 -4.82934505e-01
   1.26709998e-01 -1.65553942e-01 -7.13529408e-01  1.06903806e-01
   5.41837513e-01  4.64272827e-01 -1.78598927e-03 -3.05436134e-01
   6.36432469e-01  7.39506364e-01  3.55700999e-01 -2.52115220e-01
  -1.91619843e-01 -1.66713133e-01 -4.41559374e-01  4.70821410e-01
  -2.97358811e-01 -1.06692230e-02 -7.30748698e-02  3.64844382e-01
  -2.32469812e-01  5.59167087e-01 -1.98400751e-01 -2.37760901e-01
   8.14612746e-01 -1.36045264e-02  3.96085680e-01  1.13271511e+00
  -8.22882652e-01 -3.37269545e-01 -3.00359935e-01 -2.26665020e-01
   9.18349683e-01 -4.58473377e-02 -2.71298438e-02  3.97032611e-02
  -7.19407946e-02 -3.04297544e-02 -1.63553283e-01  6.06187642e-01
  -4.47120130e-01  4.71597821e-01 -3.90418470e-01 -5.93741946e-02
   1.02376187e+00  3.47629547e-01  5.65018654e-01 -1.66987389e-01
  -2.45777294e-01  1.71488777e-01 -1.06245244e+00 -2.50355065e-01
   7.89089382e-01 -1.32647520e-02  2.66042173e-01 -5.66755414e-01
  -8.42369437e-01  5.20819664e-01 -1.01278968e-01 -8.87298584e-03
   3.48821096e-02 -5.13995349e-01  2.53685623e-01  6.88205302e-01
   2.79835071e-02  2.08684221e-01 -2.86103785e-01 -6.18932188e-01
   2.77277142e-01 -1.23135209e-01 -4.09289747e-01  8.01149681e-02
  -2.68031266e-02 -3.97147387e-01 -3.65423530e-01 -8.86936307e-01
   1.38585126e+00 -6.18458390e-01  2.08151698e-01  1.75876141e-01
  -4.65485543e-01  5.35370827e-01  4.10381585e-01 -1.70604557e-01
   7.96300769e-02  1.82226434e-01  1.53971791e-01  8.81129876e-02
  -1.43642798e-01  2.46414632e-01 -1.52178019e-01 -7.43089378e-01
  -2.15609044e-01  1.63770691e-01 -8.17358613e-01  2.18627453e-01
   4.77873355e-01  2.87811369e-01 -3.91659796e-01 -1.88226148e-01]
 [ 4.10303995e-02  4.94479865e-01  3.33368868e-01 -2.27226093e-01
  -1.83590829e-01  1.84027448e-01 -1.14594167e-02 -6.73660398e-01
  -3.61819357e-01  1.11318719e+00 -9.06904191e-02 -4.46839839e-01
  -1.26054972e-01 -2.38244444e-01  8.84118497e-01 -1.34013236e-01
  -1.97747886e-01 -3.13453257e-01 -7.64156207e-02 -8.00168738e-02
  -1.98317751e-01  1.69433907e-01  8.12680840e-01  2.71042306e-02
  -1.31082451e+00  6.99781835e-01  1.15431719e-01  8.06683421e-01
   8.34722698e-01  2.26234406e-01 -6.61704063e-01 -3.71838242e-01
   1.06223620e-01 -2.86474079e-01 -2.44331434e-01 -1.21708959e-01
  -4.48628843e-01  9.49248970e-01  7.56487370e-01  5.85762501e-01
  -3.17059875e-01  3.24685752e-01  8.15631866e-01 -3.53259832e-01
  -8.50617826e-01  4.39742804e-01  7.24182844e-01 -4.70973194e-01
  -1.32509977e-01 -1.28177196e-01  1.23674832e-01 -5.54026723e-01
   7.24515179e-03 -7.36545086e-01 -5.45596540e-01 -1.03046700e-01
  -4.03896511e-01  2.55856633e-01 -1.62924249e-02  4.95228320e-01
  -2.39564165e-01  5.01864552e-01 -2.00684778e-02 -3.14713046e-02
   3.91023129e-01  1.91916823e-01 -2.78995246e-01 -1.86699778e-01
  -5.11206210e-01  2.72527575e-01 -4.78972383e-02 -3.09510082e-01
   4.41029370e-01 -1.40998960e-01 -2.29405448e-01 -1.72938138e-01
   3.02740157e-01  1.42895430e-01 -1.68039769e-01  2.84275949e-01
   7.52214938e-02 -6.73911750e-01  4.94306237e-01 -3.87312472e-01
  -1.27345040e-01 -3.90522242e-01 -1.05013303e-01  5.08374393e-01
  -7.63082325e-01 -1.96720168e-01 -1.20963573e-01 -3.69989723e-01
   6.48337662e-01 -3.62248361e-01 -4.20905918e-01 -3.49507153e-01
  -4.16081756e-01  5.59915364e-01 -6.58271015e-01 -3.71349365e-01
  -3.02281499e-01 -1.22544415e-01 -6.12086177e-01  2.20489681e-01
   1.52394384e-01  2.90779144e-01 -4.11232173e-01  4.04299587e-01
   7.63071418e-01 -1.75454408e-01  3.77624333e-01  1.61279157e-01
  -3.64656150e-01  2.92586654e-01  4.09423299e-02  7.23375916e-01
  -2.62757242e-01 -4.02092598e-02  8.70727971e-02  6.87704831e-02
  -2.97058165e-01  2.78083533e-01 -1.75772831e-01  1.69376194e-01
   3.03122193e-01  1.78610072e-01 -3.11896624e-03  8.33458662e-01
  -1.30488622e+00 -4.59336430e-01 -4.76010405e-02 -1.97915763e-01
   5.96871614e-01 -4.84242514e-02  7.10234761e-01  1.91848665e-01
   6.12102970e-02 -2.85190903e-02  2.58652985e-01  8.04037750e-01
  -4.90148991e-01  7.16852427e-01 -3.56141984e-01 -2.72212029e-01
   7.21761584e-01  2.70810902e-01  7.05980659e-01  2.27450252e-01
  -1.77020907e-01  3.17281753e-01 -9.93507028e-01  3.01933289e-02
  -2.60980688e-02  2.01573253e-01  7.24220753e-01 -1.92983150e-01
  -2.19186217e-01  2.49558896e-01  5.65241158e-01 -8.81271243e-01
  -2.54336298e-01 -5.67598283e-01  9.35953438e-01  5.91353714e-01
   1.04310229e-01  1.18339553e-01 -2.68523157e-01 -5.03605366e-01
  -3.49394716e-02  3.35606992e-01 -5.91749959e-02  3.77619892e-01
  -6.68743551e-02 -3.08335364e-01 -7.23626316e-02 -3.59002173e-01
   8.26292157e-01 -5.81225872e-01  1.02734499e-01  2.90773481e-01
  -2.93507725e-01  2.86109686e-01  6.93385005e-01 -2.03660414e-01
   1.39769465e-01 -2.19668001e-01 -4.73974407e-01  1.99766383e-01
  -4.94295895e-01 -1.84944477e-02 -4.67535019e-01 -5.89915216e-01
   3.92656654e-01  3.30308765e-01 -9.04345036e-01  5.42256594e-01
   3.63236010e-01  1.44760743e-01 -7.46741891e-01 -6.13264740e-01]
 [ 2.88234949e-02  1.30097896e-01 -2.24754274e-01 -1.08976051e-01
   3.91809642e-01  1.43764958e-01 -1.61267161e-01  2.61413276e-01
   2.19551712e-01  2.80399770e-01 -2.34889925e-01 -4.19935808e-02
   6.96060434e-02  5.37371859e-02  3.24899882e-01  9.01576430e-02
  -4.05172884e-01  1.72638185e-02  4.75846641e-02 -1.40124649e-01
  -8.43539312e-02  6.10494241e-02 -2.93940037e-01  2.79582024e-01
  -6.80480659e-01  2.40843460e-01  5.57841122e-01 -1.07702471e-01
  -3.18173498e-01  3.42346668e-01  3.40430647e-01  3.40675533e-01
  -4.36426774e-02 -8.27623531e-02  3.18877131e-01  1.13441393e-01
   1.32152647e-01  9.09646004e-02 -6.66224241e-01 -9.06470343e-02
  -2.07850281e-02  5.23037732e-01  2.22747698e-01  4.21566129e-01
   1.71721771e-01  3.16724092e-01  2.79666126e-01  7.04695471e-03
  -4.67239395e-02  1.88764945e-01 -9.26693454e-02 -4.41765159e-01
  -3.76424998e-01  3.95295732e-02 -2.34188125e-01 -1.02409221e-01
   5.11000991e-01  6.16330922e-01 -5.24991393e-01  1.88942209e-01
   4.48410451e-01  2.09628478e-01 -2.02120736e-01  1.90979540e-01
  -4.13114876e-01  2.71759760e-02 -2.13381603e-01  3.36508363e-01
  -1.37701035e-02 -4.44651674e-03  1.21399485e-01 -2.97895104e-01
   2.20562309e-01  2.80526668e-01 -1.96428835e-01  1.32632134e-02
   2.43020728e-01 -4.21180651e-02 -3.16454992e-02 -3.26702893e-01
   1.14808187e-01 -5.66393360e-02 -2.00975299e-01 -1.62993461e-01
   2.65922457e-01  3.50623637e-01 -1.31826177e-01  3.00644964e-01
   1.29401639e-01  1.17370941e-01 -5.09834945e-01  4.68556225e-01
   1.72732115e-01  5.04516125e-01  1.26332771e-02 -4.38148588e-01
   4.52628255e-01  1.41547412e-01  2.33368769e-01  1.62316114e-02
   9.59303677e-02 -2.00469583e-01  2.17277199e-01 -6.71052992e-01
  -2.13032842e-01 -1.99565455e-01  7.51673356e-02  4.85482886e-02
  -3.60385068e-02  3.62783432e-01 -2.91573554e-01 -4.38121855e-02
   2.58697127e-03 -1.02562986e-01  1.24687411e-01  9.85068008e-02
  -3.52831334e-01  3.51509631e-01  5.98460555e-01 -5.35352938e-02
   1.84013680e-01  3.46030116e-01  1.00643031e-01 -2.49476954e-01
   1.32931665e-01  1.64748222e-01 -5.29346764e-02 -9.00091603e-02
  -2.62398303e-01 -3.74422997e-01  1.52161613e-01 -3.00197918e-02
   1.08916946e-01  2.18702316e-01  6.84880093e-02  6.42494023e-01
  -4.06951457e-01  1.56568989e-01 -1.61667392e-01 -4.07858104e-01
   2.38899305e-03  7.49910101e-02 -3.02761167e-01 -1.33130923e-01
   1.88768446e-01 -6.06039278e-02 -7.53742596e-03  7.34155238e-01
  -1.25269294e-01 -3.64286244e-01 -1.94471568e-01  8.38633850e-02
  -7.62170777e-02  2.86726594e-01 -3.07083707e-02 -3.43869597e-01
  -7.29088187e-02 -3.27831954e-02 -2.05562070e-01  8.84812996e-02
  -5.29123396e-02  1.64367650e-02  2.57059664e-01 -3.06957632e-01
   2.38676220e-01 -2.15019509e-01 -3.53204638e-01  2.94106812e-05
   1.72951184e-02  1.85586866e-02  4.23777476e-02  1.05912052e-01
   8.37852955e-02 -3.83538455e-01  3.29182833e-01  1.26976222e-01
  -1.93369538e-01  2.77222663e-01  2.73470804e-02 -1.86452612e-01
  -2.75344789e-01 -5.38895965e-01  2.75898665e-01  1.37762696e-01
  -1.15171835e-01  1.02311082e-01  2.13568956e-01  7.92699829e-02
   6.66445121e-02  1.09340489e-01 -9.43511501e-02  8.02577510e-02
   1.23142131e-01  1.32422969e-01  1.70300424e-01  2.21575379e-01
  -2.47273177e-01  1.07035503e-01  1.07330225e-01 -5.20667247e-02]]

### Exercise 1(g) (10 points)

Build a neural network as follows:

- Build a neural network as follows:
   - `BatchNormalization()` layer.
   - `Dense` layer with 64 neurons and `activation=mish`.
   - `Dropout(0.1)`
   - `Dense` with 1 neuron `activation=None`.
- Use `optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)`, and `loss='MeanAbsoluteError'`.
- Train the network over 5 folds.
- Use `epochs=10` and `batch_size=32`. 
- Report the 5-fold mean absolute error. 

Use `X` as the inpute and `wine_df[points]` as the target variable.

In [7]:
from sklearn.model_selection import KFold as kf
from sklearn.metrics import mean_absolute_error

y = wine_df['points']

md1 = tf.keras.models.Sequential([
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(64, activation='mish', input_shape= (X.shape,)),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(1)
])

md1.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.001), loss = 'MeanAbsoluteError')

# k fold
kfold = kf(n_splits=5, shuffle=True)
scores = []

for i, (train_idx, test_idx) in enumerate(kfold.split(X,y)):
    X_train, x_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    
    md1.fit(X_train, y_train, epochs = 10, batch_size = 32, verbose=0)
    
    y_pred = md1.predict(x_test, batch_size=32, verbose=False)
    MAE = mean_absolute_error(y_pred, y_test)
    scores.append(MAE)
    print(f'Fold {i+1}, {MAE}')
    
print('average MAE', np.mean(scores))

c:\Users\gmgma\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Fold 1, 1.677174740494341
Fold 2, 1.6221395549640625
Fold 3, 1.5820860311307567
Fold 4, 1.5261524241823796
Fold 5, 1.6943251209239956
average MAE 1.620375574339107

### Exercise 1(h) (10 points)

Build a neural network as follows:

- Build a neural network as follows:
   - `BatchNormalization()` layer.
   - `Dense` layer with 64 neurons and `activation=mish`.
   - `Dropout(0.1)`.
   - `Dense` layer with 64 neurons and `activation=mish`.
   - `Dropout(0.1)`.
   - `Dense` with 1 neuron `activation=None`.
- Use `optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)`, and `loss='MeanAbsoluteError'`.
- Train the network over 5 folds.
- Use `epochs=10` and `batch_size=32`. 
- Report the 5-fold mean absolute error. 

Use `X` as the inpute and `wine_df[points]` as the target variable.

In [8]:
md2 = tf.keras.models.Sequential([
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(64, activation='mish', input_shape= (X.shape,)),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(64, activation='mish'),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(1)
])

md2.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.001), loss = 'MeanAbsoluteError')

# k fold
kfold = kf(n_splits=5, shuffle=True)
scores = []

for i, (train_idx, test_idx) in enumerate(kfold.split(X,y)):
    X_train, x_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    
    md2.fit(X_train, y_train, epochs = 10, batch_size = 32, verbose=0)
    
    y_pred = md2.predict(x_test, batch_size=32, verbose=False)
    MAE = mean_absolute_error(y_pred, y_test)
    scores.append(MAE)
    print(f'Fold {i+1}, {MAE}')
    
print('average MAE', np.mean(scores))

c:\Users\gmgma\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Fold 1, 1.723238830801202
Fold 2, 1.6195797152342022
Fold 3, 1.535391100280109
Fold 4, 1.5232732863373744
Fold 5, 1.548645829607764
average MAE 1.5900257524521304

### Exercise 1(i) (3 points)

Based on the results from parts 1(g) and 1(h), what model would you use to predict `score`? Please, be specific.

Based on my results i would use model 2 because it has the lowest MAE