# Exercise 1 (4 points)

Which prescriptive method is considered the most widely used according to the literature?

- (a) Machine learning
- (b) Mathematical programming
- (c) Simulations
- (d) Decision trees
- (e) None of the above

B

# Exercise 2 (4 points)

Briefly describe the difference between stochastic and non-stochastic prescriptive methods.

Non stochastic methods do not directly incorporate randomness and focus on determinist processes and stocastic methods explicityly account for random variations

# Exercise 3 (4 points)

Which of the following is NOT one of the six categories of prescriptive methods outlined by Lepeniotia et al. (2020)?

- (a) Mathematical programming
- (b) Evolutionary computation
- (c) Heuristic-based guessing
- (d) Logic-based methods
- (e) None of the above

C

# Exercise 4 (10 points)

Consider the `Bank_Churners.csv` data file. This data file contains information related to credit card customers of some bank. This is a brief description of the data:

- `CLIENTNUM` : Client number. Unique identifier for the customer holding the account
- `Attrition_Flag` : Internal event (customer activity) variable - if the account is closed then 1 else 0
- `Customer_Age` : Demographic variable - Customer's Age in Years
- `Gender` : M=Male, F=Female
- `Dependent_count` : Number of dependents
- `Education_Level` : Educational Qualification of the account holder (example: high school, college graduate, etc.)
- `Marital_Status` : Married, Single, Divorced, Unknown
- `Income_Category` : Annual Income Category of the account holder < $40K, $40K - 60K, $60K - $80K, $80K-$120K
- `Card_Category` : Product Variable - Type of Card (Blue, Silver, Gold, Platinum)
- `Months_on_book` : Period of relationship with bank
- `Total_Relationship_count` : Total no. of products held by the customer
- `Months_Inactive_12_mon` : No. of months inactive in the last 12 months
- `Contacts_Count_12_mon` : No. of Contacts in the last 12 months
- `Credit_Limit` : Credit Limit on the Credit Card
- `Total_Revolving_Bal` : Total Revolving Balance on the Credit Card
- `Avg_Open_To_Buy` : Open to Buy Credit Line (Average of last 12 months)
- `Total_Amt_Chng_Q4_Q1` : Change in Transaction Amount (Q4 over Q1)
- `Total_Trans_Amt` : Total Transaction Amount (Last 12 months)
- `Total_Trans_Ct` : Total Transaction Count (Last 12 months)
- `Total_Ct_Chng_Q4_Q1` : Change in Transaction Count (Q4 over Q1)
- `Avg_Utilization_Ratio` : Average Card Utilization Ratio

Explore the data.

In [2]:
import pandas as pd; pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Bank_Churners.csv')
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [3]:
df['Attrition_Flag'].value_counts(normalize=True)

Attrition_Flag
Existing Customer    0.83934
Attrited Customer    0.16066
Name: proportion, dtype: float64

In [4]:
df.duplicated().sum()

0

In [6]:
df.groupby('Attrition_Flag').agg({'Customer_Age': ['mean', 'std', 'min', 'max']})

                  Customer_Age
                          mean       std min max
Attrition_Flag
Attrited Customer    46.659496  7.665652  26  68
Existing Customer    46.262118  8.081157  26  73

In [9]:
df.groupby(['Attrition_Flag', 'Gender']).agg({'Customer_Age': ['mean', 'std', 'min', 'max']})

                         Customer_Age
                                 mean       std min max
Attrition_Flag    Gender
Attrited Customer F         46.623656  7.528652  26  66
                  M         46.707317  7.849911  26  68
Existing Customer F         46.421861  8.032405  26  67
                  M         46.088409  8.131264  26  73

In [10]:
df.groupby('Attrition_Flag').agg({'Dependent_count': ['mean', 'std', 'min', 'max']})

                  Dependent_count
                             mean       std min max
Attrition_Flag
Attrited Customer        2.402581  1.275010   0   5
Existing Customer        2.335412  1.303229   0   5

In [12]:
pd.crosstab(df['Attrition_Flag'], df['Education_Level'], normalize='index')

Education_Level,College,Doctorate,Graduate,High School,Post-Graduate,Uneducated,Unknown
Attrition_Flag,,,,,,,
Attrited Customer,0.094653,0.058390,0.299324,0.188076,0.056546,0.145667,0.157345
Existing Customer,0.101059,0.041882,0.310706,0.200824,0.049882,0.147059,0.148588

In [13]:
pd.crosstab(df['Attrition_Flag'], df['Marital_Status'], normalize='index')

Marital_Status     Divorced   Married    Single   Unknown
Attrition_Flag
Attrited Customer  0.074370  0.435771  0.410572  0.079287
Existing Customer  0.073765  0.468000  0.385294  0.072941

In [14]:
pd.crosstab(df['Attrition_Flag'], df['Income_Category'], normalize='index')

Income_Category,$120K +,$40K - $60K,$60K - $80K,$80K - $120K,Less than $40K,Unknown
Attrition_Flag,,,,,,
Attrited Customer,0.077443,0.166564,0.116165,0.148740,0.376152,0.114935
Existing Customer,0.070706,0.178706,0.142706,0.152118,0.346941,0.108824